name: Bug Report
description: Report a bug or unexpected behavior in R-Type.
title: "[BUG] Descriptive title of the issue"
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        Please provide as many details as possible to help us reproduce and resolve the bug.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Briefly describe the issue.
      placeholder: "Example: The game crashes when I connect to a server."

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide precise steps to reproduce the bug.
      placeholder: |
        1. Launch the application.
        2. Connect to the server.
        3. Observe the crash.

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What result did you expect?
      placeholder: "Example: The connection should establish successfully."

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Specify the OS, GCC/Clang version, etc.
      placeholder: "Example: Ubuntu 22.04, GCC 12.3, OpenGL 4.6"
